// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
///
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCA-sE1Az0FqY8im0oEf63nK0PvYxcwOxc',
    appId: '1:1074462760332:web:27dbd65e3d6a9148724aa9',
    messagingSenderId: '1074462760332',
    projectId: 'studentcount-86ff1',
    authDomain: 'studentcount-86ff1.firebaseapp.com',
    storageBucket: 'studentcount-86ff1.appspot.com',
    measurementId: 'G-Z5LX5VPJFB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAk2YumRqS2GTCm99dQWDpicb-b4AQLqik',
    appId: '1:1074462760332:android:79140e5a8ff4f93d724aa9',
    messagingSenderId: '1074462760332',
    projectId: 'studentcount-86ff1',
    storageBucket: 'studentcount-86ff1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0jx3x8jAdEynoQWxoRh_E-6xmhSpZ4jg',
    appId: '1:1074462760332:ios:c82351301fa6c49b724aa9',
    messagingSenderId: '1074462760332',
    projectId: 'studentcount-86ff1',
    storageBucket: 'studentcount-86ff1.appspot.com',
    iosBundleId: 'com.example.studentCount',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB0jx3x8jAdEynoQWxoRh_E-6xmhSpZ4jg',
    appId: '1:1074462760332:ios:2fa730a4e28705cb724aa9',
    messagingSenderId: '1074462760332',
    projectId: 'studentcount-86ff1',
    storageBucket: 'studentcount-86ff1.appspot.com',
    iosBundleId: 'com.example.studentCount.RunnerTests',
  );
}
